### PR TITLE
Add download command

### PR DESCRIPTION
**Pull request by lupus590**
Works like install but doesn't touch startup file.

Also, changes install command so to not duplicate code.

### CODE REVIEW

**Comment by SquidDev** [comment]
Thanks!

**Comment by lupus590** [comment]
No problem, use case was for me though, got sick of having to remove duplicates from my startup file. (Now I'm thinking of making another pull request so that MBS can figure out if it needs to add to the startup file.)

**Comment by SquidDev** [comment]
It should only append to the file if it needs to, strange.

**Comment by lupus590** [comment]
It might be because my file is in rom and it's expecting itself to be in root.

**Pull request merged**
